// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeDAwlxk-WEZapzY6E0B7_ebbr0ly4uus',
    appId: '1:1010285769775:web:285b9581191b0f0c6142da',
    messagingSenderId: '1010285769775',
    projectId: 'datavault-fc957',
    authDomain: 'datavault-fc957.firebaseapp.com',
    storageBucket: 'datavault-fc957.appspot.com',
    measurementId: 'G-0SRLBK1H0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmtafeC87WlJCWF4VFwXBaFenF5GL88kg',
    appId: '1:1010285769775:android:8683e532c6b026086142da',
    messagingSenderId: '1010285769775',
    projectId: 'datavault-fc957',
    storageBucket: 'datavault-fc957.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdpaCI3ccR5TLTupiBmTe6zRs8knzjs1U',
    appId: '1:1010285769775:ios:b42a98b99fcbb6316142da',
    messagingSenderId: '1010285769775',
    projectId: 'datavault-fc957',
    storageBucket: 'datavault-fc957.appspot.com',
    iosBundleId: 'com.example.dataVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdpaCI3ccR5TLTupiBmTe6zRs8knzjs1U',
    appId: '1:1010285769775:ios:b42a98b99fcbb6316142da',
    messagingSenderId: '1010285769775',
    projectId: 'datavault-fc957',
    storageBucket: 'datavault-fc957.appspot.com',
    iosBundleId: 'com.example.dataVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeDAwlxk-WEZapzY6E0B7_ebbr0ly4uus',
    appId: '1:1010285769775:web:6e80ef528fd142ab6142da',
    messagingSenderId: '1010285769775',
    projectId: 'datavault-fc957',
    authDomain: 'datavault-fc957.firebaseapp.com',
    storageBucket: 'datavault-fc957.appspot.com',
    measurementId: 'G-1PV38GBNXW',
  );
}
